---
#controls lxd versions, if changed, check epel version and repo urls
centos_releasever: 7
ubuntu_releasever: bionic
ansible_ssh_user: xvia
ansible_ssh_private_key_file: ~/.ssh/xvia_rsa.pub
xroad_instance: EE